version: 1.0.{build}
image: Visual Studio 2019 Preview

shallow_clone: true
clone_depth: 1

install:
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW32
  - set PreferredToolArchitecture=x86
  - choco install nasm
  - set PATH="C:\Program Files\NASM";%PATH%
  
build_script:
  - 7z a fbn-code.7z %APPVEYOR_BUILD_FOLDER%\*      
  - msbuild "projectfiles\visualstudio-2019\fba_vs2019.sln" /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild "projectfiles\visualstudio-2019\fba_vs2019.sln" /m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && mingw32-make mingw510 -j20 RELEASEBUILD=1 SKIPDEPEND=1"
  - 7z a fbn-win32-gcc.7z %APPVEYOR_BUILD_FOLDER%\*.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html      
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && rm -rf obj && mingw32-make mingw510 -j20 SKIPDEPEND=1"
  - 7z a fbn-win32-debug-gcc.7z %APPVEYOR_BUILD_FOLDER%\fbneod.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html %APPVEYOR_BUILD_FOLDER%\projectfiles\visualstudio-2019\generated\gamelist.txt       
  - 7z a fbn-win32-vs.7z %APPVEYOR_BUILD_FOLDER%\projectfiles\visualstudio-2019\Win32\Release\*.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html %APPVEYOR_BUILD_FOLDER%\projectfiles\visualstudio-2019\generated\gamelist.txt     
  - 7z a fbn-x64-vs.7z %APPVEYOR_BUILD_FOLDER%\projectfiles\visualstudio-2019\x64\Release\*.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html %APPVEYOR_BUILD_FOLDER%\projectfiles\visualstudio-2019\generated\gamelist.txt      
   
artifacts:
  - path: fbn-code.7z
    name: source
  - path: fbn-win32-vs.7z
    name: win32-bin-vs
  - path: fbn-x64-vs.7z
    name: x64-bin-vs  
  - path: fbn-win32-gcc.7z
    name: win32-bin-gcc  
  - path: fbn-win32-debug-gcc.7z
    name: win32-bin-debug-gcc	
# Test scripts
test: off

deploy:
- provider: GitHub
  tag: appveyor-build
  description: github-commit-%APPVEYOR_REPO_COMMIT%
  force_update: true
  on:
    branch: master                 # release from master branch only 
  auth_token:
    secure: cC6FjF22axzOF1Y1+B2DfieS+B3KAHeUTefa7k/iq7MJjqaj/OjQ01EWN+Ga5r6v
  repository: finalburnneo/FBNeo-WIP-Storage-Facility
  artifact: win32-bin-vs, x64-bin-vs, source, win32-bin-gcc, win32-bin-debug-gcc
