name: VS2019 x64 CI

on: [push]

jobs:
  buildvsx64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild x64
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fba_vs2010.vcxproj /m /property:Configuration=Release /property:Platform=x64 /verbosity:minimal
#    - name: make artifacts
#      run: |
#           mkdir fbn-x64-vs
#           cd fbn-x64-vs
#           cp ../projectfiles/visualstudio-2019/x64/Release/*.exe .
#           cp ../fba.chm .
#           cp ../*.zip .
#           cp ../src/license.txt .
#           cp ../whatsnew.html .
#    - name: upload vs x64 artifacts
#      uses: actions/upload-artifact@v1
#      with:
#        name: fbn-x64-vs
#        path: fbn-x64-vs
