name: VS2019 win32 CI

on: [push]

jobs:
  buildvsx86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild x86
      working-directory: projectfiles/visualstudio-2019
      run: |
           msbuild fbn_vs2019.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: make artifacts
      run: |
           mkdir fbn-win32-vs
           cd fbn-win32-vs
           cp ../projectfiles/visualstudio-2019/Win32/Release/*.exe .
           cp ../fba.chm .
           cp ../*.zip .
           cp ../src/license.txt .
           cp ../whatsnew.html .
    - name: upload vs x86 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fbn-win32-vs
        path: fbn-win32-vs
